# Generated by Django 3.1.3 on 2020-11-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.TextField(blank=True, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('wikipage', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
